PACT_BROKER_PORT="9292"
PACT_BROKER_DATABASE_URL="postgres://username:password@postgres/postgres"
PACT_BROKER_LOG_LEVEL=INFO
PACT_BROKER_SQL_LOG_LEVEL=DEBUG
PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES="5"