version: "3"

services:
  postgres:
    image: postgres:15.2
    healthcheck:
      test: psql postgres --command "select 1" - U postgres
    env_file:
      - .envs/.postgres

  pact-broker:
    image: pactfoundation/pact-broker:2.107.0.1
    ports:
      - "9292:9292"
    depends_on:
      - postgres
    env_file:
      - .envs/.pact